'use client'

// import type { Metadata } from "next";
import { Vazirmatn } from 'next/font/google'
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/store";

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const vazir = Vazirmatn({
    subsets: ['latin'],
    display: 'swap',
  })


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Provider store={store} >
        <body
            className={`${vazir.className} antialiased`}
        >
            {children}
            <ToastContainer />
        </body>
      </Provider>
    </html>
  );
}
