'use client'

import type { Metadata } from "next";
import { Vazirmatn } from 'next/font/google'
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/store";
import useAuth from "@/hooks/useAuth";
import { useRouter } from "next/navigation";

const vazir = Vazirmatn({
    subsets: ['latin'],
    display: 'swap',
  })


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const router = useRouter()
    const {user , error ,loading}=useAuth()

    if(loading){
        return <h2>Loading</h2>
    }

    if(error){
        router.push('/auth/login')
    }

    console.log(user)
  return (
    <html lang="en">
      <Provider store={store} >
        <body
            className={`${vazir.className} antialiased`}
        >
            {children}
        </body>
      </Provider>
    </html>
  );
}
