'use client'

import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/store";

import { Vazirmatn } from 'next/font/google'

///Toastify
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const vazir = Vazirmatn({ subsets: ['latin'] })

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Provider store={store}>
        <body
            className={`${vazir.className} antialiased`}
        >
            {children}
            <ToastContainer />
        </body>
      </Provider>
    </html>
  );
}
